languageCode = "en-us"
title = "ODINTALE"
theme = "hugo-html5up-alpha"
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "<Your Name>'s blog"
  subtitle    = "Blog | Tutorial"
  pageNotFoundTitle = "404 - Page not found"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 200
